do switch between envs

diff --git a/.github/actions/deploy-setup/action.yml b/.github/actions/deploy-setup/action.yml
--- a/.github/actions/deploy-setup/action.yml
+++ b/.github/actions/deploy-setup/action.yml
@@ -12,7 +12,18 @@ runs:
       id: load-env
       run: |
         echo ${{ inputs.environment }} > .last_used_env
-        echo "${{ secrets[format('env_{0}', inputs.environment)] }}" > ".env.${{ inputs.environment }}"
+ 
+         # Switch between environments
+        if [ "${{ inputs.environment }}" = "staging" ]; then
+          echo "${{ secrets.ENV_STAGING }}" > ".env.${{ inputs.environment }}"
+        elif [ "${{ inputs.environment }}" = "foxtrot" ]; then
+          echo "${{ secrets.ENV_FOXTROT }}" > ".env.${{ inputs.environment }}"
+        elif [ "${{ inputs.environment }}" = "juliett" ]; then
+          echo "${{ secrets.ENV_JULIETT }}" > ".env.${{ inputs.environment }}"
+        else
+          echo "Error: Unknown environment ${{ inputs.environment }}"
+          exit 1
+        fi
 
         echo "GCP_REGION=${GCP_REGION}" >> $GITHUB_ENV
         echo "TERRAFORM_STATE_BUCKET=${TERRAFORM_STATE_BUCKET}" >> $GITHUB_ENV
